# SPDX-License-Identifier: LGPL-2.1-or-later

"""Static reference for the VibeScript authoring API and execution contract.

The payload is generated by introspecting :mod:`vibescript_api` so it can
never drift from the real authoring surface: every name in
``vibescript_api.__all__`` is documented with its signature and one-line
summary, alongside the execution namespace, the static import policy, the
sandbox builtins, and the execution budget.
"""

from __future__ import annotations

import inspect
from typing import Any

import vibescript_api
import vibescript_executor
import VibeCADVibeScript


TOOL_SPEC = {
    "name": "vibescript.describe_api",
    "description": (
        "Return the complete VibeScript authoring reference: signature and "
        "one-line summary for every helper injected into the execution "
        "namespace (SketchBuilder, pad, pocket, revolve, loft, polar_pattern, "
        "edges, Params, ...), the injected names (doc, params), the result "
        "output contract, the static import policy with allowed module roots, "
        "the available sandbox builtins, and the execution budget. Call this "
        "once before writing the first VibeScript source; it is a static "
        "reference that never reads or mutates the document."
    ),
    "contextual": True,
    "safety": "READ",
    "workbench": "PartDesignWorkbench",
    "requires_document": False,
    "edit_modes": ["none"],
    "parameters": {
        "type": "object",
        "properties": {},
        "additionalProperties": False,
    },
}


def _summary(obj: Any) -> str:
    """First non-empty docstring line, or empty string."""
    doc = inspect.getdoc(obj) or ""
    for line in doc.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _signature(obj: Any) -> str | None:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return None


def _method_entries(cls: type) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for name, member in inspect.getmembers(cls):
        if name.startswith("_"):
            continue
        if isinstance(member, property):
            entries.append(
                {
                    "name": name,
                    "kind": "property",
                    "signature": None,
                    "summary": _summary(member),
                }
            )
        elif callable(member):
            entries.append(
                {
                    "name": name,
                    "kind": "method",
                    "signature": _signature(member),
                    "summary": _summary(member),
                }
            )
    return entries


def _api_entry(name: str) -> dict[str, Any]:
    obj = getattr(vibescript_api, name)
    if inspect.isclass(obj):
        if issubclass(obj, BaseException):
            return {
                "name": name,
                "kind": "exception",
                "signature": _signature(obj),
                "summary": _summary(obj),
            }
        return {
            "name": name,
            "kind": "class",
            "signature": _signature(obj),
            "summary": _summary(obj),
            "methods": _method_entries(obj),
        }
    if inspect.isfunction(obj):
        return {
            "name": name,
            "kind": "function",
            "signature": _signature(obj),
            "summary": _summary(obj),
        }
    return {
        "name": name,
        "kind": "value",
        "signature": None,
        "summary": str(obj),
    }


def run(service: Any) -> dict[str, Any]:
    del service  # Static reference: no document or session state is read.
    return {
        "ok": True,
        "engine": "vibescript",
        "api": [_api_entry(name) for name in vibescript_api.__all__],
        "namespace": {
            "injected": sorted({"doc", "params", *vibescript_api.__all__}),
            "doc": (
                "The live FreeCAD document. Create bodies with new_body(doc); "
                "never call FreeCAD.newDocument()."
            ),
            "params": (
                "Validated flat numeric parameters (vibescript_api.Params) "
                "from the tool call, readable as attributes or mapping keys."
            ),
            "result_contract": (
                "Assign result to a dict whose keys exactly match "
                "expected_outputs and whose values are document objects each "
                "owning exactly one valid solid. All lengths are millimetres; "
                "angles are degrees."
            ),
            "stdout": (
                "print() output is captured (bounded) and returned as stdout "
                "in every success and failure payload."
            ),
        },
        "policy": {
            "allowed_import_roots": sorted(vibescript_executor.ALLOWED_IMPORT_ROOTS),
            "disallowed_calls": sorted(VibeCADVibeScript._DISALLOWED_CALLS),
            "builtins": sorted(vibescript_executor._BUILTIN_ALLOWLIST),
            "enforcement": (
                "Source is validated statically (AST) before execution; "
                "violations are rejected before the document is touched. Do "
                "not probe the sandbox at runtime."
            ),
        },
        "budget": {
            "max_seconds": vibescript_executor.DEFAULT_MAX_SECONDS,
            "max_operations": vibescript_executor.DEFAULT_MAX_OPERATIONS,
            "max_stdout_chars": vibescript_executor.MAX_STDOUT_CHARS,
            "note": (
                "The wall-clock budget includes native FreeCAD recompute time "
                "inside the transaction."
            ),
        },
    }
